### ISSUE TITLE
[Feature Request] Ability to Upload Normal Files

### ISSUE THREAD

**Issue by ossie-git** [microsoft/avml#11]
One of the neat features in AVML is the ability to securely upload to cloud storage using pre-signed URLs. This is a feature that I haven't seen often in other tools (you typically need your cloud credentials on the target machine which is dangerous). Would it be possible to add the ability to upload a normal file instead of just memory captures? This may be useful in cases where you haven't determined yet whether you need to perform a full investigation that warrants a full disk backup + full memory capture. Thanks

**Comment by bmc-msft** [comment]
For Azure blob store with SAS tokens, you may find [azcopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10) a viable solution.

I will investigate adding an additional executable that uses the already developed upload capabilities.

**Comment by bmc-msft** [comment]
@ossie-git I'm sorry for the delay.

The linked PR should include this feature.  Can you give this a shot and let me know if it meets your needs?

The included `avml-upload` has significantly fewer features than `azcopy` but is also significantly smaller.

**Comment by ossie-git** [comment]
Hi,

Thank you for implementing this feature. I tested it out on an S3 bucket and it seems to fail while the equivalent **curl** command succeeds (so I know the pre-signed upload URL is valid). Here is what it looks like :

```
# ./avml-upload --url 'https://mybucket.s3.amazonaws.com/YourKey?AWSAccessKeyId=AKIAAAAAAAAAAAAAA&Expires=1604802978&Signature=%2FgCDSPFuW6Q7ENyudQzJ%2FapFH6o%3D' file
Error: "unable to upload to file"
```

So it failed. I then tried it with the full path:

```
# ./avml-upload --url 'https://mybucket.s3.amazonaws.com/YourKey?AWSAccessKeyId=AKIAAAAAAAAAAAAAA&Expires=1604802978&Signature=%2FgCDSPFuW6Q7ENyudQzJ%2FapFH6o%3D' /root/file
Error: "unable to upload to file"
```

again, it failed. When I use the same URL with curl, it works:

```
# curl --request PUT --upload-file /root/file 'https://mybucket.s3.amazonaws.com/YourKey?AWSAccessKeyId=AKIAAAAAAAAAAAAAA&Expires=1604802978&Signature=%2FgCDSPFuW6Q7ENyudQzJ%2FapFH6o%3D'
```

The file I was trying to upload was small (6.6 MB). Any ideas? Thanks.

**Comment by ossie-git** [comment]
Hi,

Thank you for implementing this. However, in my testing, it failed. I tested it out on an S3 bucket and it seems to fail while the equivalent curl command succeeds (so I know the pre-signed upload URL is valid). Here is what it looks like :

```
# ./avml-upload --url 'https://mybucket.s3.amazonaws.com/YourKey?AWSAccessKeyId=AKIAAAAAAAAAAAAAA&Expires=1604802978&Signature=%2FgCDSPFuW6Q7ENyudQzJ%2FapFH6o%3D' file
Error: "unable to upload to file"
```

So it failed. I then tried it with the full path:

```
# ./avml-upload --url 'https://mybucket.s3.amazonaws.com/YourKey?AWSAccessKeyId=AKIAAAAAAAAAAAAAA&Expires=1604802978&Signature=%2FgCDSPFuW6Q7ENyudQzJ%2FapFH6o%3D' /root/file
Error: "unable to upload to file"
```

again, it failed. When I use the same URL with curl, it works:

```
# curl --request PUT --upload-file /root/file 'https://mybucket.s3.amazonaws.com/YourKey?AWSAccessKeyId=AKIAAAAAAAAAAAAAA&Expires=1604802978&Signature=%2FgCDSPFuW6Q7ENyudQzJ%2FapFH6o%3D'
```

Any ideas? Am I missing something? Thanks

**Comment by vvadymv** [comment]
The same behavior as @ossie-git facing:
```
13:00:42 lnx-lab3:~ # ./avml test2 --url 'https://<redacted>.s3.amazonaws.com/test2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=3600&X-Amz-Credential=<redacted>%2F20201216%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Date=20201216T175055Z&X-Amz-Signature=8351a94f9be740a8db59074cc0196afd1465d022badf1c69ed4c3c9af5ed7920'
Error: Error(Hyper(Error(ChannelClosed)), "https://<redacted>.s3.amazonaws.com/test2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=3600&X-Amz-Credential=<redacted>%2F20201216%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Date=20201216T175055Z&X-Amz-Signature=8351a94f9be740a8db59074cc0196afd1465d022badf1c69ed4c3c9af5ed7920")
```
But it's ok with curl:
```
curl -i --request PUT --upload-file test2 "https://<redacted>.s3.amazonaws.com/test2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=3600&X-Amz-Credential=<redacted>%2F20201216%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Date=20201216T175055Z&X-Amz-Signature=8351a94f9be740a8db59074cc0196afd1465d022badf1c69ed4c3c9af5ed7920"
```
