### ISSUE TITLE
Splitting memory dump before S3 upload

### ISSUE THREAD

**Issue by dfir-man131** [microsoft/avml#118]
Would there be a way for you all to split the resulting memory dump into parts less than 5GB once acquired and then ship to S3?  Running into issues with hitting the 5GB AWS pre-signed URL upload while trying to ship the full memory file.  The mem is being compressed, however it still exceeds this 5GB limit.  Any insight would be greatly appreciated! Thanks!

**Comment by bmc-msft** [comment]
You should be able to use a tool like GNU coreutils [split](https://www.gnu.org/software/coreutils/split) to split the files prior to uploading.  If you're using `split`, try the `--bytes=size` argument.

We would be open to a contribution that adds support for [multi-part uploads](https://docs.rs/aws-sdk-s3/0.15.0/aws_sdk_s3/struct.Client.html#method.create_multipart_upload) using the [AWS S3 SDK](https://docs.rs/aws-sdk-s3/0.15.0/aws_sdk_s3/).

**Comment by chadbrewbaker** [comment]
How about this - I PR a python script https://github.com/microsoft/avml/tree/main/eng/s3Example.py?

Splits the file into 4G chunks and uploads each chunk to a list of S3 presigned URIs located in a config.toml?

**Comment by demoray** [comment]
The difficulty with including such a script is maintaining it moving forward.  

We are not likely to implement this request at this time, though we would be receptive to a PR that implements this as a compile-time feature.
