### ISSUE TITLE
I have successfully built on 32-bit architecture

### ISSUE THREAD

**Issue by yakuter** [microsoft/avml#130]
Hi, thanks for this great project.

I needed to use this in i686 (32) bit architecture. So I tried to build from source code. I used the following steps.
```bash
sudo apt-get install musl-dev musl-tools musl
curl https://sh.rustup.rs -sSf | sh -s -- -y
rustup target add i686-unknown-linux-musl
cargo build --release --target i686-unknown-linux-musl
cargo build --release --target i686-unknown-linux-musl --no-default-features
```

The only problem was block size calculations in **src/upload/blobstore.rs** which overflows in 32 bit Linux. 
```rust
const BLOB_MAX_BLOCKS: usize = 50_000;
const BLOB_MAX_BLOCK_SIZE: usize = ONE_MB * 4000;
const BLOB_MAX_FILE_SIZE: usize = BLOB_MAX_BLOCKS * BLOB_MAX_BLOCK_SIZE;
const BLOB_MIN_BLOCK_SIZE: usize = ONE_MB * 5;
const MAX_CONCURRENCY: usize = 10;
const REASONABLE_BLOCK_SIZE: usize = ONE_MB * 100;
```
Because I am not going to use blob storage upload feature, I changed them almost like zero.

After this little change I have successfully built and made it work on 32 bit.

Hope this helps you on your work for 32 bit support. Because I don't know Rust, I can't open a PR for this.

**Comment by bmc-msft** [comment]
If you're not using the blob features, those can be turned off via the `--no-default-features` to your `cargo build` command, which will not include the blob or HTTP upload features.

**Comment by yakuter** [comment]
Thank you very much. I missed the line in the documentation about --no-default-features. It works fine on both 32bit Centos and Ubuntu. 👍
