### ISSUE TITLE
Error while running on Amazon Linux 2

### ISSUE THREAD

**Issue by dfir-man131** [microsoft/avml#18]
Attempting to get avml to run on an amazon linux 2 instance (uname -r == 4.14.225-168.357.amzn2.x86_64), however continue to get an "Unable to read physical memory" error.

Steps taken:

1. Logged onto instance as ec2-user and elevated to root
2. Pulled down the latest release-v0.2.1 of AVML via wget (md5:4d360eba0cdba02adf0900f64ae3dc1c), ran "chmod +x avml"
3. Ran (as root) "./avml memory.mem", got above mentioned error
4. Also tried "./avml --compress memory.mem", got same error

I have also attempted building avml with rust/cargo, tested on a ubuntu vm (it worked), transferred over to the AL2 instance, got same error.  Please assist! Thank you.

**Comment by bmc-msft** [comment]
Can you verify you have read access to /dev/crash, /proc/kcore, or /dev/mem?

**Comment by dfir-man131** [comment]
![image](https://user-images.githubusercontent.com/79167752/114903450-d2d1c800-9de4-11eb-9deb-e1acbe9daad5.png)

**Comment by dfir-man131** [comment]
Still looking for some assistance on this one...Also seeing another somewhat related issue when running on a t2.xlarge vs. t2.micro.  Here is a side-by-side of the 2 instances (both same kernel, same avml, different size mem xlarge vs. micro) 
![avml_probs](https://user-images.githubusercontent.com/79167752/116903838-f41b1c80-ac0a-11eb-94c0-094b79834180.png)

**Comment by bmc-msft** [comment]
@dfir-man131, if you're building from source, please try PR #20.  This adds detailed context to the error conditions, hopefully this will help debug this issue.

If you are not using source, are you able to download the build artifacts from this pipeline?

https://dev.azure.com/ms/avml/_build/results?buildId=162945&view=artifacts&pathAsName=false&type=publishedArtifacts

If so, please try that build of `avml` and paste the errors here.   Note: It's helpful to include the standard out & error as text rather than a screenshot.  Thanks.

**Comment by dfir-man131** [comment]
Below is the output from using the provided avml package...

[ec2-user@ip- ~]$ sudo ./avml --compress mem
unable to read memory
/dev/crash failed: unable to create image. source:/dev/crash destination:mem

Caused by:
    0: unable to open source file: /dev/crash
    1: No such file or directory (os error 2)
/proc/kcore failed: unable to copy block: 4294967296..34628173824

Caused by:
    0: unable to copy block: 16982736896..17087594496
    1: copy failed
    2: No space left on device (os error 28)
/dev/mem failed: unable to write block: 1048576:4026531839

Caused by:
    0: unable to copy block: 1048576..4026531839
    1: unable to copy block: 1048576..105906176
    2: copy failed
    3: Operation not permitted (os error 1)
Error: unable to collect memory

Caused by:
    unable to read physical memory

**Comment by bmc-msft** [comment]
Ah, ok I see the see the issue.  Your VM supports /proc/kcore, however

**Comment by bmc-msft** [comment]
(sorry, didn't mean to close the issue.)

I see the problem.  You're running out of disk space when creating the memory snapshot.

```
/proc/kcore failed: unable to copy block: 4294967296..34628173824

Caused by:
0: unable to copy block: 16982736896..17087594496
1: copy failed
2: No space left on device (os error 28)
```
