### ISSUE TITLE
Binary not available ?

### ISSUE THREAD

**Issue by fpusersuggest** [microsoft/avml#19]
Hello,
would very nice to have binary instead of source because it's a big problem to compile it in an airgapped machine. 
My router and my pc are infected and I want take a ram dump by avml but I need to built it in an offline machine, if I connect the clean machine to internet by the infected router even the clean machine will be infected. Then I have to take everything i need to built avml by the infected and online machine. Then to be honest it's a complicated and not risk less job.
To have binaries for main distributions like ubuntu would be very appreciated.

**Comment by bmc-msft** [comment]
Binaries are distributed as part of the releases on GitHub.

https://github.com/microsoft/avml/releases

**Comment by bmc-msft** [comment]
Note, as binaries these are built with [musl](https://musl.libc.org/), they should work on any X86_64 linux distro.  That said, we test almost exclusively on Azure using [these images](https://github.com/microsoft/avml#tested-distributions).
