### ISSUE TITLE
Rasberry Pi4 based Kali linux Platform execution issue

### ISSUE THREAD

**Issue by ReninRoy** [microsoft/avml#247]
./avml binary giving error "ELF not Found" Syntax error showing. is this  avml release version 0.9.0  binary file format supported on Raspberry Pi4.

**Comment by ReninRoy** [comment]
is there any method to capture memory dump of kail linux running on Raspberry Pi4

**Comment by demoray** [comment]
@ReninRoy, can you share the full output that you're seeing?

**Comment by ReninRoy** [comment]
![avml eror](https://user-images.githubusercontent.com/122520441/214496619-b14906c0-1420-45d8-87b5-4fc27c6823c2.png)

**Comment by demoray** [comment]
I understand the issue you are experiencing.  The `avml` executables that are published as part of this project are compiled for x86_64 Linux.  Raspberry Pi requires ARM executables, not x86_64.  If you compile AVML yourself, it is likely to run successfully on Kali on Raspberry Pi.

This project will seek to include ARM executables once hosted GitHub Actions runners support ARM64.  (ref: https://github.com/actions/runner-images/issues/5631)
