### ISSUE TITLE
Build fails with only 'put' feature enabled.

### ISSUE THREAD

**Issue by svdb0** [microsoft/avml#249]
Building AVML fails when only the `put` feature is enabled, as in `cargo build --release --no-default-features --features put`.

There are two causes:
* The `put` feature of AVML requires `tokio-util`, but `tokio-util` is not listed as a dependency of `put` in `Cargo.toml`.
* The `put` feature of AVML requires the `stream` feature of the `reqwest` dependency, which is not enabled in `Cargo.toml`.  
  A full-featured build of AVML does not fail, so presumably the `stream` feature of `reqwest` is indirectly enabled by some other dependency.

**Comment by demoray** [comment]
This issue has been addressed.  The next release will include the changes that both fix this issue and ensure we do not hit similar issues in the future.   Thank you for your report.

**Comment by demoray** [comment]
The fix for this issue was released as part of https://github.com/microsoft/avml/releases/tag/v0.11.0
