### ISSUE TITLE
[Request] Output to stdout

### ISSUE THREAD

**Issue by moxilo** [microsoft/avml#34]
Thank you for the amazing tool. One request for the team. Could it be possible to send the output to stdout instead to a file? A lot of times the space on the disk is smaller than the size of the memory, and compress is not enough. Currently I am using CIFS, S3FS or mounting an additional volume into the VM and format it to be able to dump into an external storage that it is mounted locally. However this creates unwanted artefacts. 

If I was able to send output to stdout, I could pipe it to any of the tools to transfer files without touching disk: rsync, aws s3, scp, etc; Thank you!

NOTE: aware of the risk of delaying the memory acquisition due to dumping to an external device, but usually if same data center we are talking about 150-100 mb/s

**Comment by bmc-msft** [comment]
@moxilo, you should be able to use `/dev/stdout` as the output file, which enables sending the output to stdout instead of a file.

I've used this method to acquire memory from remote machines over an SSH session.

**Comment by moxilo** [comment]
Thanks for the answer. I tried via /dev/stdout by AVML behaviour is erratic.

This works:
```
echo "joaquin test" | /usr/bin/aws s3 cp --expected-size 13 - s3://asdf/test1.avml --acl bucket-owner-full-control
```

This also:
```
SIZE=$(du -b /bin/ls | awk {'print $1'})
cat /bin/ls | /usr/bin/aws s3 cp --expected-size $SIZE - s3://asdf/test2.avml --acl bucket-owner-full-control
```

However, when I try with AVML:
```
grep MemTotal /proc/meminfo | awk '{print $2 * 1024}'
32655360000
./avml  --compress /dev/stdout | /usr/bin/aws s3 cp --expected-size 32655360000 - s3://asdf/test3.avml --acl bucket-owner-full-control
(immediate crash)
unable to read memory
/dev/crash failed: unable to create image. source:/dev/crash destination:/dev/stdout

Caused by:
    0: unable to open source file: /dev/crash
    1: No such file or directory (os error 2)
/proc/kcore failed: unable to copy block: 4096..651264

Caused by:
    0: unable to copy block: 4096..651264
    1: unable to seek to location
    2: Invalid seek (os error 29)
/dev/mem failed: unable to write block: 4096:654335

Caused by:
    0: unable to copy block: 4096..654335
    1: unable to copy block: 4096..654335
    2: unable to seek to location
    3: Invalid seek (os error 29)
Error: unable to collect memory

Caused by:
    unable to read physical memory
    
```

and without compress:

```
./avml  /dev/stdout | /usr/bin/aws s3 cp --expected-size 32655360000 - s3://asdf/test4.avml --acl bucket-owner-full-control
(it crashes after a while)
```

Manual dump worked:
```
./avml /dev/stdout >> test.txt
```

**Comment by bmc-msft** [comment]
Can you try `avml --compress --source /proc/kcore /dev/stdout | aws s3 cp ...`

**Comment by bmc-msft** [comment]
As I hinted in my previous comment, I identified a potential problem when writing to `/dev/stdout` without specifying a source.  This may be partially responsible for the instability you were seeing.

If the user doesn't specify a source, `avml` iterates over `/dev/crash`, `/proc/kcore`, and `/dev/mem` to attempt to read memory.  If one fails, it starts over and tries the next one on the list.  With any other output file, this is fine (and preferred, given some of the 3rd party kernel lockdown patches I've come across)

PR https://github.com/microsoft/avml/pull/35 should address the concern I identified.

**Comment by moxilo** [comment]
Specifying the output worked for me. We are now checking if kcore is available, and if it is, we run against kcore. If it is not available, we run against crash.  I have not tested yet 0.4.1 to see if fix the problem, I will test it tomorrow (sorry for the delay)

**Comment by moxilo** [comment]
We have tested with 0.3 binary provided in the repo and we have compile the last available version (0.4.1) with same results. When /dev/stdout is used with compress, it fails:

- Work: avml --source /proc/kcore /dev/stdout 
- Does NOT work: avml --source /proc/kcore --compress /dev/stdout >> image.raw
- Work: avml --source /proc/kcore /dev/stdout | aws s3 cp  ...
- Does NOT work: avml --source /proc/kcore --compress /dev/stdout | aws s3 cp  ...

Example:
```
sudo ./avml --compress --source /proc/kcore /dev/stdout 
AVML?Error: unable to collect memory

Caused by:
    0: unable to copy block: 4096..647168
    1: unable to copy block: 4096..647168
    2: unable to seek to location
    3: Invalid seek (os error 29)
```

**Comment by bmc-msft** [comment]
Interesting.  Can you share the VM instant type and `/proc/iomem`?  I'd like to dig into that more.  I've not seen that in any of the VMs I've interacted with thus far.

**Comment by moxilo** [comment]
Yes sure:

```
# uname -r
5.10.68-62.173.amzn2.x86_64
# cat /etc/image-id
image_name="amzn2-ami-kernel-5.10-hvm"
image_version="2"
image_arch="x86_64"
image_file="amzn2-ami-kernel-5.10-hvm-2.0.20211103.0-x86_64.xfs.gpt"
image_stamp="8c91-3a82"
image_date="20211108205243"
recipe_name="xxxx"
recipe_id="xxxxx"
# curl http://169.254.169.254/latest/meta-data/ami-id
ami-097607527741dc147
# curl http://169.254.169.254/latest/meta-data/instance-type
m1.large
#
```

```
# cat /proc/iomem
00000000-00000fff : Reserved
00001000-0009dfff : System RAM
0009e000-0009ffff : Reserved
000a0000-000bffff : PCI Bus 0000:00
000c0000-000c8bff : Video ROM
000e0000-000fffff : Reserved
  000f0000-000fffff : System ROM
00100000-efffffff : System RAM
  01000000-01c02fb6 : Kernel code
  01e00000-024bcfff : Kernel rodata
  02600000-02f371ff : Kernel data
  03548000-03bfffff : Kernel bss
f0000000-fbffffff : PCI Bus 0000:00
  f0000000-f1ffffff : 0000:00:02.0
  f2000000-f2ffffff : 0000:00:03.0
    f2000000-f2ffffff : xen-platform-pci
  f3000000-f3000fff : 0000:00:02.0
fc000000-ffffffff : Reserved
  fec00000-fec003ff : IOAPIC 0
  fed00000-fed003ff : HPET 0
    fed00000-fed003ff : PNP0103:00
  fee00000-fee00fff : Local APIC
100000000-1efffffff : System RAM
```

And taking System RAM, total 7.5GB of ram which it is what we see:
```
>>> a = 0x0009dfff - 0x00001000
>>> b = 0xefffffff - 0x00100000
>>> c = 0x1efffffff - 0x100000000
>>> (a + b + c) / 1024 / 1024
7679.613278388977
>>> (a + b + c) / 1024 / 1024 / 1024
7.499622342176735
```

**Comment by bmc-msft** [comment]
@moxilo, can you try PR #48?  

You should be able to get pre-built artifacts from our [ADO pipeline](https://dev.azure.com/ms/avml/_build/results?buildId=265233&view=artifacts&pathAsName=false&type=publishedArtifacts).

**Comment by moxilo** [comment]
@bmc-msft thank you for working on this. Yes changing seek by counter did the trick. It is working now. Thank you
