### ISSUE TITLE
Documentation how to decompress memory images compressed with avml

### ISSUE THREAD

**Issue by kosherpork** [microsoft/avml#4]
The README shows how to compress a memory dump but not how to decompress it. Is there a tool available to decompress it?

**Comment by bmc-msft** [comment]
One will be available soon.

**Comment by bmc-msft** [comment]
avml-convert was added in [v0.1.2](/microsoft/avml/releases/tag/v0.1.2)

To write a compressed file:
`avml-convert --compress ./input.lime ./output.lime`

To write a decompressed file:
`avml-convert ./input.lime ./output.lime`
