### ISSUE TITLE
How to check current version of AVML binary?

### ISSUE THREAD

**Issue by evild3ad** [microsoft/avml#72]
May you add the previous existing option argument -V again? Thank you!

**Comment by evild3ad** [comment]
You can simply add the version to the help message and file hashes to the
release page. Thank you!

bmc-msft ***@***.***> schrieb am Mo. 21. März 2022 um 15:42:

**Comment by bmc-msft** [comment]
The change that adds `--version` will be included in the next release.

**Comment by evild3ad** [comment]
Thanks! 👍
