### ISSUE TITLE
unable to read memory

### ISSUE THREAD

**Issue by Kalis1eka** [microsoft/avml#73]
i have some eror when i memory dump the eror is unable to read memory
please for solutions

**Comment by bmc-msft** [comment]
Can you share the output from AVML here?

**Comment by Kalis1eka** [comment]
Pada tanggal Sab, 19 Mar 2022 00.58, bmc-msft ***@***.***>
menulis:

**Comment by Kalis1eka** [comment]
> Can you share the output from AVML here?

**Comment by Kalis1eka** [comment]
> Can you share the output from AVML here?

ubuntu@UbuntuNet:~/Desktop$ sudo ./avml memory.dmp
Error: error: unable to read memory
caused by:
    0: unable to create memory snapshot:     
        error: unable to create memory snapshot from source: /dev/crash
        caused by:
            0: unable to create memory snapshot
            1: unable to read memory
            2: No such file or directory (os error 2)
        
        error: unable to create memory snapshot from source: /proc/kcore
        caused by:
            0: unable to find memory range: 1793703960..1793750615
        
        error: unable to create memory snapshot from source: /dev/mem
        caused by:
            0: unable to create memory snapshot
            1: write block failed: 1048576..1793703959
